export const categoriesNameMap = {
    "/men": "Men",
    "/men/clothing": "Clothing",
    "/men/clothing/jackets": "Jackets",
    "/men/clothing/t-shirts": "T-Shirts",
    "/men/footwear": "Footwear",
    "/men/footwear/sneakers": "Sneakers",
    "/men/footwear/boots": "Boots",
    "/men/accessories": "Accessories",
    "/men/accessories/watches": "Watches",
    "/men/accessories/belts": "Belts",
    "/women": "Women",
    "/women/clothing": "Clothing",
    "/women/clothing/dresses": "Dresses",
    "/women/clothing/tops": "Tops",
    "/women/footwear": "Footwear",
    "/women/footwear/heels": "Heels",
    "/women/footwear/flats": "Flats",
    "/women/accessories": "Accessories",
    "/women/accessories/handbags": "Handbags",
    "/women/accessories/jewelery": "Jewelery",
};
